default:
  http_metas:
    content-type: text/html

  metas:
    title:        mazemod
    #description:  symfony project
    #keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    []

  javascripts:    ["swfobject.js", "jquery-latest.js", "jquery.history.js", "jquery.heartbeat.js"]

  has_layout:     on
  layout:         layout
